//! A C transpiler: a second backend that emits portable C99 from
//! [`Hir`](crate::hir).
//!
//! # Scope
//!
//! This backend targets the **scalar subset** of Lumen - `i64`, `f64`, `bool`,
//! and `unit`, with functions, recursion, and all control flow. The heap types
//! (`str`, arrays, structs) would require a reference-counted C runtime; rather
//! than ship a half-finished one, the transpiler reports a clear
//! [`CError::Unsupported`] when it meets them. Programs in the scalar subset
//! transpile to clean, warning-free C that any C99 compiler accepts.
//!
//! # How it works
//!
//! Lumen and C are both expression/statement languages, but Lumen's `if` and
//! blocks are *expressions*. The emitter flattens those: a value-position `if`
//! evaluates each arm into a fresh temporary and the surrounding expression
//! reads it, mirroring the strategy used by [MIR construction](crate::mir).
//! Integer arithmetic is emitted with explicit wrapping helpers so it matches
//! the VM's semantics exactly.

use std::fmt::Write as _;

use crate::hir::{BinOp, Block, Callee, Expr, ExprKind, Function, Hir, Stmt, UnOp};
use crate::sema::types::{Builtin, Type};

/// Why C generation failed.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum CError {
    #[error("the C backend does not support {0} (only the scalar subset is supported)")]
    Unsupported(&'static str),
}

/// Transpiles a program to a self-contained C99 translation unit.
#[tracing::instrument(level = "debug", skip_all)]
pub fn emit_c(hir: &Hir) -> Result<String, CError> {
    let fn_names = hir.functions.iter().map(|f| f.name.clone()).collect();
    let mut e = Emitter {
        out: String::new(),
        tmp: 0,
        depth: 0,
        fn_names,
    };
    e.preamble();
    // Forward declarations so functions may call each other in any order.
    for func in &hir.functions {
        let proto = e.signature(func)?;
        let _ = writeln!(e.out, "{proto};");
    }
    e.out.push('\n');
    for func in &hir.functions {
        e.function(func)?;
    }
    e.main_shim(hir);
    Ok(e.out)
}

struct Emitter {
    out: String,
    tmp: usize,
    depth: usize,
    /// Function names indexed by `FnId`, for resolving call targets.
    fn_names: Vec<String>,
}

impl Emitter {
    fn preamble(&mut self) {
        self.out.push_str(
            "/* Generated by the Lumen compiler. */\n\
             #include <stdint.h>\n\
             #include <stdbool.h>\n\
             #include <stdio.h>\n\n\
             static inline int64_t lm_add(int64_t a, int64_t b) { return (int64_t)((uint64_t)a + (uint64_t)b); }\n\
             static inline int64_t lm_sub(int64_t a, int64_t b) { return (int64_t)((uint64_t)a - (uint64_t)b); }\n\
             static inline int64_t lm_mul(int64_t a, int64_t b) { return (int64_t)((uint64_t)a * (uint64_t)b); }\n\n",
        );
    }

    fn fresh(&mut self) -> String {
        let t = format!("t{}", self.tmp);
        self.tmp += 1;
        t
    }

    fn indent(&mut self) {
        for _ in 0..self.depth {
            self.out.push_str("    ");
        }
    }

    fn line(&mut self, text: &str) {
        self.indent();
        self.out.push_str(text);
        self.out.push('\n');
    }

    /// The C function signature for a Lumen function (no trailing `;`).
    fn signature(&self, func: &Function) -> Result<String, CError> {
        let ret = c_type(func.ret)?;
        let params = func
            .params()
            .iter()
            .enumerate()
            .map(|(i, p)| c_type(p.ty).map(|t| format!("{t} _{i}")))
            .collect::<Result<Vec<_>, _>>()?
            .join(", ");
        let params = if params.is_empty() {
            "void".to_string()
        } else {
            params
        };
        Ok(format!("static {ret} {}({params})", c_name(&func.name)))
    }

    fn function(&mut self, func: &Function) -> Result<(), CError> {
        let proto = self.signature(func)?;
        let _ = writeln!(self.out, "{proto} {{");
        self.depth += 1;
        // Declare non-parameter locals (parameters are C function arguments).
        for (i, local) in func.locals.iter().enumerate().skip(func.param_count) {
            let ty = c_type(local.ty)?;
            self.line(&format!("{ty} _{i} = {};", zero_value(local.ty)));
        }
        // The body is a value-producing block; compute it and return it.
        let value = self.expr_block(&func.body)?;
        if matches!(func.ret, Type::Unit) {
            // Unit functions still return an `int64_t` (0) so a call is always a
            // valid C value expression; the result is discarded by callers.
            self.line(&format!("(void)({value});"));
            self.line("return 0;");
        } else {
            self.line(&format!("return {value};"));
        }
        self.depth -= 1;
        self.out.push_str("}\n\n");
        Ok(())
    }

    /// Emits a block in value position, returning a C expression for its value.
    fn expr_block(&mut self, block: &Block) -> Result<String, CError> {
        for stmt in &block.stmts {
            self.stmt(stmt)?;
        }
        match &block.tail {
            Some(tail) => self.expr(tail),
            None => Ok("0".to_string()),
        }
    }

    fn stmt(&mut self, stmt: &Stmt) -> Result<(), CError> {
        match stmt {
            Stmt::Let { local, value } => {
                let v = self.expr(value)?;
                self.line(&format!("_{} = {v};", local.0));
            }
            Stmt::Expr(e) => {
                let v = self.expr(e)?;
                self.line(&format!("(void)({v});"));
            }
            Stmt::Return(value) => match value {
                Some(e) => {
                    let v = self.expr(e)?;
                    self.line(&format!("return {v};"));
                }
                None => self.line("return;"),
            },
            Stmt::While { cond, body } => {
                self.line("while (1) {");
                self.depth += 1;
                let c = self.expr(cond)?;
                self.line(&format!("if (!({c})) break;"));
                let v = self.expr_block(body)?;
                self.line(&format!("(void)({v});"));
                self.depth -= 1;
                self.line("}");
            }
            Stmt::For {
                var,
                end_var,
                start,
                end,
                body,
            } => {
                let s = self.expr(start)?;
                self.line(&format!("_{} = {s};", var.0));
                let e = self.expr(end)?;
                self.line(&format!("_{} = {e};", end_var.0));
                self.line(&format!("while (_{} < _{}) {{", var.0, end_var.0));
                self.depth += 1;
                let v = self.expr_block(body)?;
                self.line(&format!("(void)({v});"));
                self.line(&format!("_{0} = lm_add(_{0}, 1);", var.0));
                self.depth -= 1;
                self.line("}");
            }
            Stmt::Break => self.line("break;"),
            Stmt::Continue => self.line("continue;"),
        }
        Ok(())
    }

    /// Emits an expression, returning a C expression string for its value.
    /// Side-effecting or statement-shaped forms emit preceding statements and
    /// return a temporary.
    fn expr(&mut self, expr: &Expr) -> Result<String, CError> {
        match &expr.kind {
            ExprKind::Int(v) => Ok(format!("INT64_C({v})")),
            ExprKind::Float(v) => Ok(format!("{v:?}")),
            ExprKind::Bool(v) => Ok(if *v { "true".into() } else { "false".into() }),
            ExprKind::Str(_) => Err(CError::Unsupported("strings")),
            ExprKind::Local(id) => Ok(format!("_{}", id.0)),
            ExprKind::Unary { op, rhs } => {
                let r = self.expr(rhs)?;
                Ok(match op {
                    UnOp::Neg if rhs.ty == Type::Int => format!("lm_sub(0, {r})"),
                    UnOp::Neg => format!("(-{r})"),
                    UnOp::Not => format!("(!{r})"),
                })
            }
            ExprKind::Binary { op, lhs, rhs } => self.binary(*op, lhs, rhs),
            ExprKind::Call { callee, args } => self.call(*callee, args, expr.ty),
            ExprKind::Assign { local, value } => {
                let v = self.expr(value)?;
                self.line(&format!("_{} = {v};", local.0));
                Ok("0".to_string())
            }
            ExprKind::If {
                cond,
                then_branch,
                else_branch,
            } => self.if_expr(cond, then_branch, else_branch.as_deref(), expr.ty),
            ExprKind::Block(block) => self.expr_block(block),
            ExprKind::ArrayLit(_) | ExprKind::Index { .. } | ExprKind::SetIndex { .. } => {
                Err(CError::Unsupported("arrays"))
            }
            ExprKind::StructLit(_) | ExprKind::GetField { .. } | ExprKind::SetField { .. } => {
                Err(CError::Unsupported("structs"))
            }
        }
    }

    fn binary(&mut self, op: BinOp, lhs: &Expr, rhs: &Expr) -> Result<String, CError> {
        // Short-circuit operators map directly onto C's.
        let l = self.expr(lhs)?;
        let r = self.expr(rhs)?;
        let is_int = lhs.ty == Type::Int;
        Ok(match op {
            BinOp::Add if is_int => format!("lm_add({l}, {r})"),
            BinOp::Sub if is_int => format!("lm_sub({l}, {r})"),
            BinOp::Mul if is_int => format!("lm_mul({l}, {r})"),
            BinOp::Add => format!("({l} + {r})"),
            BinOp::Sub => format!("({l} - {r})"),
            BinOp::Mul => format!("({l} * {r})"),
            BinOp::Div => format!("({l} / {r})"),
            BinOp::Rem => format!("({l} % {r})"),
            BinOp::Eq => format!("({l} == {r})"),
            BinOp::Ne => format!("({l} != {r})"),
            BinOp::Lt => format!("({l} < {r})"),
            BinOp::Le => format!("({l} <= {r})"),
            BinOp::Gt => format!("({l} > {r})"),
            BinOp::Ge => format!("({l} >= {r})"),
            BinOp::And => format!("({l} && {r})"),
            BinOp::Or => format!("({l} || {r})"),
        })
    }

    fn call(&mut self, callee: Callee, args: &[Expr], ret: Type) -> Result<String, CError> {
        let arg_strs = args
            .iter()
            .map(|a| self.expr(a))
            .collect::<Result<Vec<_>, _>>()?;
        match callee {
            Callee::Fn(id) => {
                let name = c_name(&self.fn_names[id.0 as usize]);
                Ok(format!("{name}({})", arg_strs.join(", ")))
            }
            Callee::Builtin(b) => self.builtin_call(b, &arg_strs, ret),
        }
    }

    fn builtin_call(&mut self, b: Builtin, args: &[String], _ret: Type) -> Result<String, CError> {
        let arg = args.first().cloned().unwrap_or_default();
        match b {
            Builtin::PrintInt => {
                self.line(&format!("printf(\"%lld\\n\", (long long)({arg}));"));
                Ok("0".to_string())
            }
            Builtin::PrintFloat => {
                self.line(&format!("printf(\"%g\\n\", (double)({arg}));"));
                Ok("0".to_string())
            }
            Builtin::PrintBool => {
                self.line(&format!(
                    "printf(\"%s\\n\", ({arg}) ? \"true\" : \"false\");"
                ));
                Ok("0".to_string())
            }
            // Integer math maps onto C expressions (no libm needed).
            Builtin::AbsInt => Ok(format!("(({arg}) < 0 ? lm_sub(0, {arg}) : ({arg}))")),
            Builtin::MinInt => {
                let b = args.get(1).cloned().unwrap_or_default();
                Ok(format!("(({arg}) < ({b}) ? ({arg}) : ({b}))"))
            }
            Builtin::MaxInt => {
                let b = args.get(1).cloned().unwrap_or_default();
                Ok(format!("(({arg}) > ({b}) ? ({arg}) : ({b}))"))
            }
            // String, array, and float-math builtins need a C runtime / libm.
            _ => Err(CError::Unsupported("this builtin in the C backend")),
        }
    }

    fn if_expr(
        &mut self,
        cond: &Expr,
        then_branch: &Block,
        else_branch: Option<&Expr>,
        ty: Type,
    ) -> Result<String, CError> {
        let result = self.fresh();
        let cty = c_type(ty)?;
        self.line(&format!("{cty} {result} = {};", zero_value(ty)));
        let c = self.expr(cond)?;
        self.line(&format!("if ({c}) {{"));
        self.depth += 1;
        let then_val = self.expr_block(then_branch)?;
        self.line(&format!("{result} = {then_val};"));
        self.depth -= 1;
        self.line("} else {");
        self.depth += 1;
        let else_val = match else_branch {
            Some(e) => self.expr(e)?,
            None => "0".to_string(),
        };
        self.line(&format!("{result} = {else_val};"));
        self.depth -= 1;
        self.line("}");
        Ok(result)
    }

    /// Emits a C `main` that calls the Lumen entry point.
    fn main_shim(&mut self, hir: &Hir) {
        let entry = &hir.functions[hir.main.0 as usize];
        let _ = writeln!(
            self.out,
            "int main(void) {{ {}(); return 0; }}",
            c_name(&entry.name)
        );
    }
}

/// The C type for a Lumen scalar type.
fn c_type(ty: Type) -> Result<&'static str, CError> {
    match ty {
        Type::Int => Ok("int64_t"),
        Type::Float => Ok("double"),
        Type::Bool => Ok("bool"),
        Type::Unit => Ok("int64_t"),
        Type::Error => Ok("int64_t"),
        Type::Str => Err(CError::Unsupported("strings")),
        Type::Array(_) => Err(CError::Unsupported("arrays")),
        Type::Struct(_) => Err(CError::Unsupported("structs")),
        Type::Tuple(_) => Err(CError::Unsupported("tuples")),
    }
}

/// A zero-initialiser for a scalar type.
fn zero_value(ty: Type) -> &'static str {
    match ty {
        Type::Float => "0.0",
        Type::Bool => "false",
        _ => "0",
    }
}

/// Mangles a Lumen function name into a valid, collision-free C identifier.
fn c_name(name: &str) -> String {
    format!("lm_fn_{name}")
}

#[cfg(test)]
mod tests;
