//! A peephole optimizer over generated bytecode.
//!
//! After the HIR optimizer and code generation, the instruction stream can
//! still contain local redundancies that are only visible at the bytecode
//! level. This pass cleans two of them up, per chunk:
//!
//! * **Jump threading.** A jump whose target is itself an unconditional `Jump`
//!   is retargeted directly to the final destination, skipping the trampoline.
//! * **Push/pop elimination.** A side-effect-free push immediately followed by
//!   a `Pop` computes a value that is discarded; both instructions are removed.
//!
//! Removing instructions renumbers the chunk, so every jump target is remapped
//! through an old-to-new index table. The pass never touches an instruction
//! that is itself a jump target, which keeps the remapping exact and the
//! transformation behaviour-preserving. A test asserts that optimized and
//! unoptimized programs produce identical output.

use crate::backend::bytecode::{Chunk, Op, Program};

/// Runs the peephole optimizer over every chunk of a program in place.
#[tracing::instrument(level = "debug", skip_all)]
pub fn optimize(program: &mut Program) -> usize {
    let mut removed = 0;
    for chunk in &mut program.functions {
        loop {
            thread_jumps(chunk);
            let n = eliminate_push_pop(chunk);
            removed += n;
            if n == 0 {
                break;
            }
        }
    }
    tracing::debug!(removed, "peephole optimization complete");
    removed
}

/// Retargets jumps that point at an unconditional `Jump`, following chains.
fn thread_jumps(chunk: &mut Chunk) {
    let len = chunk.code.len();
    let resolve = |mut target: usize| -> usize {
        let mut guard = 0;
        while guard < len {
            match chunk.code.get(target) {
                Some(Op::Jump(next)) if *next != target => {
                    target = *next;
                    guard += 1;
                }
                _ => break,
            }
        }
        target
    };
    // Collect the resolved targets first to avoid borrowing while mutating.
    let resolved: Vec<(usize, usize)> = chunk
        .code
        .iter()
        .enumerate()
        .filter_map(|(i, op)| match op {
            Op::Jump(t) | Op::JumpIfFalse(t) => Some((i, resolve(*t))),
            _ => None,
        })
        .collect();
    for (i, target) in resolved {
        match &mut chunk.code[i] {
            Op::Jump(t) | Op::JumpIfFalse(t) => *t = target,
            _ => {}
        }
    }
}

/// Removes pure `push; pop` pairs and renumbers jump targets.
///
/// Returns the number of instructions removed.
fn eliminate_push_pop(chunk: &mut Chunk) -> usize {
    let targets = jump_targets(chunk);
    let n = chunk.code.len();
    let mut remove = vec![false; n];

    let mut i = 0;
    while i + 1 < n {
        let is_pure_push = matches!(
            chunk.code[i],
            Op::PushInt(_)
                | Op::PushFloat(_)
                | Op::PushBool(_)
                | Op::PushUnit
                | Op::PushStr(_)
                | Op::LoadLocal(_)
        );
        let pop_follows = matches!(chunk.code[i + 1], Op::Pop);
        // Only fuse when neither instruction is the destination of a jump, so
        // removing them cannot strand a branch.
        if is_pure_push && pop_follows && !targets.contains(&i) && !targets.contains(&(i + 1)) {
            remove[i] = true;
            remove[i + 1] = true;
            i += 2;
        } else {
            i += 1;
        }
    }

    let removed = remove.iter().filter(|&&r| r).count();
    if removed == 0 {
        return 0;
    }

    // Build the old-index -> new-index map: a removed instruction maps to where
    // the next surviving instruction lands (so any jump to it stays valid).
    let mut new_index = vec![0usize; n + 1];
    let mut next = 0;
    for (old, &gone) in remove.iter().enumerate() {
        new_index[old] = next;
        if !gone {
            next += 1;
        }
    }
    new_index[n] = next;

    let old_code = std::mem::take(&mut chunk.code);
    for (old, op) in old_code.into_iter().enumerate() {
        if remove[old] {
            continue;
        }
        chunk.code.push(remap(op, &new_index));
    }
    removed
}

/// The set of instruction indices that some jump targets.
fn jump_targets(chunk: &Chunk) -> std::collections::HashSet<usize> {
    chunk
        .code
        .iter()
        .filter_map(|op| match op {
            Op::Jump(t) | Op::JumpIfFalse(t) => Some(*t),
            _ => None,
        })
        .collect()
}

/// Rewrites a jump's target through the index map; leaves other ops unchanged.
fn remap(op: Op, new_index: &[usize]) -> Op {
    match op {
        Op::Jump(t) => Op::Jump(new_index[t]),
        Op::JumpIfFalse(t) => Op::JumpIfFalse(new_index[t]),
        other => other,
    }
}

#[cfg(test)]
mod tests;
